from email.message import EmailMessage
import smtplib


class Emailsender:
    def __init__(self, subject: str = 'Alert Intruder Detected', sender: str = 'accesscontoler@gmail.com',
                 receiver: str = '', 
                 content: str = "be careful there is a unknown person close from  your house.") -> None:
        self.sender = sender
        # Password generated by App passwords from Google
        self.password = 'hijo gkgw mwff kpvi'

        self.msg = EmailMessage()
        self.msg['Subject'] = subject
        self.msg['From'] = sender
        self.msg['To'] = receiver
        self.msg.set_content(content)

    def sendEmail(self):
        # Set up the SMTP server and send the email
        try:
            with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
                smtp.login(self.sender, self.password)
                smtp.send_message(self.msg)
                return True
        except Exception:
            return False
        